import type { Config } from "tailwindcss";

export default {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./Screens/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#0076d3",
        "surface-tint": "#ad3300",
        "surface-bright": "#fff8f6",
        "inverse-primary": "#ffb59e",
        "outline-variant": "#e6beb2",
        "on-primary-container": "#fffbff",
        "inverse-surface": "#3f2c26",
        error: "#ba1a1a",
        secondary: "#505f76",
        tertiary: "#005da8",
        "secondary-fixed-dim": "#b7c8e1",
        "on-error": "#ffffff",
        "surface-container-high": "#ffe2da",
        "secondary-container": "#d0e1fb",
        "on-primary-fixed": "#3a0b00",
        outline: "#916f65",
        "primary-fixed": "#ffdbd0",
        "on-secondary-container": "#54647a",
        "surface-container": "#ffe9e3",
        "on-error-container": "#93000a",
        "on-tertiary-fixed": "#001c39",
        "on-tertiary-fixed-variant": "#004884",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "primary-container": "#d34000",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#0b1c30",
        "surface-container-highest": "#fbdcd3",
        surface: "#fff8f6",
        "inverse-on-surface": "#ffede8",
        "on-primary": "#ffffff",
        "tertiary-fixed-dim": "#a4c9ff",
        "primary-fixed-dim": "#ffb59e",
        "on-tertiary-container": "#fdfcff",
        "surface-variant": "#fbdcd3",
        "on-background": "#281712",
        primary: "#a93100",
        "on-tertiary": "#ffffff",
        "on-surface-variant": "#5c4037",
        "tertiary-fixed": "#d4e3ff",
        "surface-container-low": "#fff1ed",
        "on-surface": "#281712",
        background: "#fff8f6",
        "on-primary-fixed-variant": "#842500",
        "surface-dim": "#f2d3ca",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-fixed-variant": "#38485d",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        md: "1rem",
        gutter: "1rem",
        lg: "1.5rem",
        "margin-mobile": "1rem",
        xl: "2rem",
        sm: "0.5rem",
        "margin-desktop": "2.5rem",
        base: "4px",
        xs: "0.25rem",
        "2xl": "3rem",
      },
      fontFamily: {
        epilogue: ["var(--font-epilogue)", "ui-sans-serif", "system-ui", "sans-serif"],
        "display-lg": ["var(--font-epilogue)", "ui-sans-serif", "system-ui", "sans-serif"],
        "headline-md": ["var(--font-epilogue)", "ui-sans-serif", "system-ui", "sans-serif"],
        "title-sm": ["var(--font-be-vietnam)", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-sm": ["var(--font-be-vietnam)", "ui-sans-serif", "system-ui", "sans-serif"],
        "body-md": ["var(--font-be-vietnam)", "ui-sans-serif", "system-ui", "sans-serif"],
        "label-caps": ["var(--font-be-vietnam)", "ui-sans-serif", "system-ui", "sans-serif"],
        // Legacy (used in older classnames)
        display: ["var(--font-epilogue)", "ui-sans-serif", "system-ui", "sans-serif"],
        body: ["var(--font-be-vietnam)", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      fontSize: {
        "title-sm": ["18px", { lineHeight: "1.4", fontWeight: "600" }],
        "headline-md": [
          "24px",
          { lineHeight: "1.2", fontWeight: "700", letterSpacing: "-0.01em" },
        ],
        "display-lg": [
          "40px",
          { lineHeight: "1.1", fontWeight: "700", letterSpacing: "-0.02em" },
        ],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
} satisfies Config;
